String boolState(uint8_t raw,const char*offText,const char*onText){if(raw==0)return String(offText);if(raw==0xFF)return String(onText);return"Raw 0x"+hex2(raw);}
void markSessionLost(const String&why){diagnosticSession=false;cr2Connected=false;livePolling=false;lastError=why;activity("Diagnostic session lost: "+why);setStatus("SESSION LOST");if(autoReconnect)reconnectAtMs=millis()+2000;}
void notePollResult(bool ok){if(ok){consecutiveRequestFailures=0;return;}if(++consecutiveRequestFailures>=3)markSessionLost("Three consecutive diagnostic requests failed");}
bool connectFastModule(ModuleId module){activity("Connecting to "+moduleName(module)+" at address 0x"+hex2(moduleAddr(module))+" on OBD pin "+String(moduleObdPin(module)));busy=true;livePolling=false;diagnosticSession=false;cr2Connected=false;activeModule=module;requestedModule=module;activeEcuAddr=moduleAddr(module);consecutiveRequestFailures=0;keepaliveMisses=0;lastError="";setStatus("CONNECTING - "+moduleName(module));releaseKL();delay(cfg.preIdleMs);pinMode(TX_PIN,OUTPUT);digitalWrite(TX_PIN,gpioForKLow());delayMicroseconds(25000);digitalWrite(TX_PIN,gpioForKHigh());delayMicroseconds(25000);uartOn();flushRx();uint8_t startPayload[1]={0x81},tx[16];size_t tn=buildKwpFrame(startPayload,1,tx,sizeof(tx));sendSpacedBytes(tx,tn);uint8_t raw[256],frame[128];size_t fn=0;size_t rn=readRaw(raw,sizeof(raw),900,cfg.rxQuietMs);lastRxHex=bytesHex(raw,rn);if(!rn||!extractEcuFrame(raw,rn,frame,fn,sizeof(frame))){lastError="No valid StartCommunication response from "+moduleName(module);activity("Connection failed: "+lastError);setStatus("CONNECT FAILED");releaseKL();busy=false;return false;}const uint8_t*rp=nullptr;size_t rpn=0;if(!responsePayload(frame,fn,rp,rpn)||rpn<1||rp[0]!=0xC1){lastError="Unexpected StartCommunication response: "+bytesHex(frame,fn);activity("Connection failed: "+lastError);setStatus("CONNECT FAILED");releaseKL();busy=false;return false;}lastRxHex=bytesHex(frame,fn);lastGoodTrafficMs=millis();p3ReadyAtMs=millis()+cfg.p3MinMs;diagnosticSession=true;cr2Connected=(module==MOD_ENGINE);keepaliveMisses=0;activity("Connected to "+moduleName(module)+". Live polling started.");setStatus("CONNECTED - "+moduleName(module));livePolling=true;nextPollMs=millis()+80;busy=false;return true;}
bool connectModule(ModuleId module){if(module==MOD_ENGINE){bool ok=connectCR2();if(ok){activeModule=MOD_ENGINE;activeEcuAddr=0x12;requestedModule=MOD_ENGINE;livePolling=true;nextPollMs=millis()+80;}return ok;}return connectFastModule(module);}
bool absPayload(uint8_t group,const uint8_t*frame,size_t fn,const uint8_t*&p,size_t&pn){if(!responsePayload(frame,fn,p,pn)||pn<3)return false;return p[0]==0x6A&&p[1]==0x01&&p[2]==group;}
double absWheelSpeed(uint16_t raw){return raw<=38?0.0:raw<=4800?raw*0.0625:-1.0;}
bool pollABSGroup(uint8_t group){uint8_t payload[3]={0x2A,0x01,group},r[256];size_t rn=0;bool ok=sendKwpPayload(payload,sizeof(payload),r,rn,650);if(!ok){notePollResult(false);return false;}const uint8_t*p=nullptr;size_t pn=0;if(!absPayload(group,r,rn,p,pn)){lastError="Unexpected ABS response";notePollResult(false);return false;}if(group==1&&pn>=11){double rl=absWheelSpeed(be16(p+3)),fr=absWheelSpeed(be16(p+5)),rr=absWheelSpeed(be16(p+7)),fl=absWheelSpeed(be16(p+9));if(rl>=0)setNum(absWheelRL,rl,"km/h",1);if(fr>=0)setNum(absWheelFR,fr,"km/h",1);if(rr>=0)setNum(absWheelRR,rr,"km/h",1);if(fl>=0)setNum(absWheelFL,fl,"km/h",1);}else if(group==2&&pn>=5){setNum(absVoltage,p[3]*0.071,"V",2);setNum(absWheelSensorV,p[4]*0.0196,"V",2);}else if(group==3&&pn>=14){setTxt(absBrakeLamp,boolState(p[3],"Released","Pressed"));setTxt(absBrakeSwitch,boolState(p[4],"Pressed","Released"));setTxt(absPump,boolState(p[6],"Stopped","Running"));setTxt(absOutletFL,boolState(p[9],"Not commanded","Commanded"));setTxt(absOutletFR,boolState(p[13],"Not commanded","Commanded"));}notePollResult(true);return true;}
String egsGearName(uint8_t x){switch(x){case 0:return"N";case 1:return"1";case 2:return"2";case 3:return"3";case 4:return"4";case 5:return"5";case 11:return"R";case 12:return"R2";case 13:return"P";case 14:return"Free";case 15:return"Implausible";default:return"Raw "+String(x);}}
String egsSelectorName(uint8_t x){switch(x){case 0:return"N/A";case 1:return"1";case 2:return"2";case 3:return"3";case 4:return"4";case 5:return"D";case 6:return"N";case 7:return"R";case 8:return"P";case 9:return"+";case 10:return"-";case 11:return"N-D";case 12:return"R-N";case 13:return"P-R";case 15:return"Implausible";default:return"Raw "+String(x);}}
bool pollEGSGroup(uint8_t group){uint8_t payload[2]={0x21,group},r[256];size_t rn=0;bool ok=sendKwpPayload(payload,sizeof(payload),r,rn,650);if(!ok){notePollResult(false);return false;}const uint8_t*p=nullptr;size_t pn=0;if(!responsePayload(r,rn,p,pn)||pn<2||p[0]!=0x61||p[1]!=group){lastError="Unexpected EGS response";notePollResult(false);return false;}if(group==0x30&&pn>=20){setNum(egsOutputRpm,be16(p+18),"rpm",0);setTxt(egsGear,egsGearName(p[12]));setTxt(egsSelector,egsSelectorName(p[9]));if(p[13]!=0xFF)setNum(egsTemp,(double)p[13]-50.0,"°C",0);}else if(group==0x31&&pn>=22){setNum(egsTurbineRpm,be16(p+6),"rpm",0);setNum(egsVehicleSpeed,be16(p+18)*0.1,"km/h",1);}else if(group==0x34&&pn>=10)setNum(egsBattery,be16(p+2)*0.025,"V",2);notePollResult(true);return true;}
uint8_t absPollIndex=0,egsPollIndex=0;
void absLivePollTick(){if(!livePolling||!diagnosticSession||busy||(int32_t)(millis()-nextPollMs)<0)return;static const uint8_t groups[]={1,2,3};busy=true;pollABSGroup(groups[absPollIndex++%3]);busy=false;nextPollMs=millis()+cfg.pollIntervalMs;}
void egsLivePollTick(){if(!livePolling||!diagnosticSession||busy||(int32_t)(millis()-nextPollMs)<0)return;static const uint8_t groups[]={0x30,0x31,0x34};busy=true;pollEGSGroup(groups[egsPollIndex++%3]);busy=false;nextPollMs=millis()+cfg.pollIntervalMs;}
void livePollTick(){if(activeModule==MOD_ENGINE)engineLivePollTick();else if(activeModule==MOD_ABS)absLivePollTick();else egsLivePollTick();}
String valueJson(const char*id,const char*label,const ValueState&v){return"{\"id\":\""+String(id)+"\",\"label\":\""+String(label)+"\",\"value\":\""+jsonEscape(v.text)+"\",\"unit\":\""+jsonEscape(v.unit)+"\",\"valid\":"+String(v.valid?1:0)+",\"stale\":"+String(stale(v)?1:0)+"}";}
String sensorsJson(){String s="{\"module\":\""+jsonEscape(moduleName(activeModule))+"\",\"items\":[";bool first=true;auto add=[&](const char*id,const char*label,const ValueState&v){if(!first)s+=",";first=false;s+=valueJson(id,label,v);};if(activeModule==MOD_ENGINE){add("rpm","Engine RPM",engRpm);add("speed","Vehicle speed",engSpeed);add("coolant","Coolant temperature",engCoolant);add("intake","Intake temperature",engIntake);add("boost","Boost pressure",engBoost);add("boostTarget","Boost target",engBoostTarget);add("rail","Rail pressure",engRail);add("lowFuel","Low-side fuel pressure",engLowFuel);add("battery","Battery voltage",engBattery);add("egr","EGR duty",engEgr);add("boostDuty","Boost actuator duty",engBoostDuty);}else if(activeModule==MOD_ABS){add("wheelFL","Front-left wheel",absWheelFL);add("wheelFR","Front-right wheel",absWheelFR);add("wheelRL","Rear-left wheel",absWheelRL);add("wheelRR","Rear-right wheel",absWheelRR);add("voltage","ABS supply voltage",absVoltage);add("wheelSensorV","Wheel-sensor monitor voltage",absWheelSensorV);add("brakeLamp","Brake-light switch",absBrakeLamp);add("brakeSwitch","Brake switch",absBrakeSwitch);add("pump","Pump motor feedback",absPump);add("outletFL","Front-left outlet valve",absOutletFL);add("outletFR","Front-right outlet valve",absOutletFR);}else{add("temp","Transmission temperature",egsTemp);add("gear","Actual gear",egsGear);add("selector","Selector position",egsSelector);add("outputRpm","Output shaft RPM",egsOutputRpm);add("turbineRpm","Turbine RPM",egsTurbineRpm);add("speed","Vehicle speed",egsVehicleSpeed);add("battery","TCM battery voltage",egsBattery);}s+="]}";return s;}
String moduleStatusJson(){String s="{";s+="\"firmware\":\""+String(FIRMWARE_VERSION)+"\",";s+="\"module\":\""+jsonEscape(moduleName(activeModule))+"\",";s+="\"moduleId\":"+String((int)activeModule)+",";s+="\"address\":\"0x"+hex2(activeEcuAddr)+"\",";s+="\"obdPin\":"+String(moduleObdPin(activeModule))+",";s+="\"connected\":"+String(diagnosticSession?1:0)+",";s+="\"polling\":"+String(livePolling?1:0)+",";s+="\"busy\":"+String(busy?1:0)+",";s+="\"status\":\""+jsonEscape(scannerStatus)+"\",";s+="\"error\":\""+jsonEscape(lastError)+"\",";s+="\"wifi\":\""+jsonEscape(WiFi.status()==WL_CONNECTED?WiFi.localIP().toString():WiFi.softAPIP().toString())+"\"";s+="}";return s;}
