String statusJson(){String s="{";s+="\"status\":\""+jsonEscape(scannerStatus)+"\",";s+="\"connected\":"+String(diagnosticSession?1:0)+",";s+="\"session\":"+String(diagnosticSession?1:0)+",";s+="\"polling\":"+String(livePolling?1:0)+",";s+="\"busy\":"+String(busy?1:0)+",";s+="\"lastTx\":\""+jsonEscape(lastTxHex)+"\",";s+="\"lastRx\":\""+jsonEscape(lastRxHex)+"\",";s+="\"error\":\""+jsonEscape(lastError)+"\",";s+="\"baud\":"+String(cfg.baud)+",";s+="\"spacing\":"+String(cfg.byteSpacingUs);s+="}";return s;}
String liveJson(){return"{\"text\":\""+jsonEscape(allLiveText())+"\"}";}
String advancedPage(){return R"HTML(<!doctype html><html><head><meta name=viewport content="width=device-width,initial-scale=1"><title>T1N Scanner Advanced</title><style>body{font-family:system-ui;background:#07101c;color:#eef;max-width:1000px;margin:auto;padding:16px}.c{background:#0d1928;border:1px solid #24374f;border-radius:14px;padding:14px;margin:10px 0}button,input{font:inherit;padding:9px;border-radius:8px;border:1px solid #36506d;background:#173252;color:white}button{font-weight:800}.red{background:#71343a}pre{white-space:pre-wrap;word-break:break-word;background:#050b12;padding:10px;border-radius:9px;max-height:360px;overflow:auto}a{color:#8dc0ff}.g{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:8px}.muted{color:#8ea2ba;font-size:12px}</style></head><body><a href=/>← Back to Scanner</a> · <a href=/update>Firmware Update</a><h2>Advanced / Workbench</h2><div class=muted>Raw commands and transport controls live here so the normal scanner UI stays read-only.</div>
<div class=c><b>Connection</b><p><button onclick=p('/connect')>CONNECT CR2</button> <button onclick=p('/disconnect')>DISCONNECT</button> <button onclick=p('/poll/start')>START POLL</button> <button onclick=p('/poll/stop')>STOP POLL</button></p><pre id=st>...</pre></div>
<div class=c><b>KWP payload terminal</b><p><input id=raw style="width:70%" placeholder="21 13"> <button onclick=sendRaw()>SEND</button></p><pre id=ans></pre></div>
<div class=c><b>DTC tools</b><p><button onclick=p('/dtc/read')>READ</button> <button class=red onclick=clearDtc()>CLEAR ENGINE DTCs</button></p><pre id=dtc></pre></div>
<div class=c><b>TLIN1027 channel wiring (fixed)</b><div class=muted>Each channel is directly connected; UART2 moves to the selected GPIO pair. No relays.</div><pre>Chip 1: OBD 1  · RX 13 · TX 12 (reserved)
Chip 2: OBD 7  · RX 14 · TX 27 (Engine)
Chip 3: OBD 9  · RX 26 · TX 25 (ABS)
Chip 4: OBD 11 · RX 33 · TX 32 (Transmission)</pre><pre id=relayDiag>...</pre></div>
<div class=c><b>Transport settings</b><div class=g><label>Baud<br><input id=baud></label><label>Byte spacing µs<br><input id=byteSpacingUs></label><label>Fast LOW µs<br><input id=fastLowUs></label><label>Fast first byte µs<br><input id=fastFirstByteUs></label><label>Poll groups<br><input id=pollGroups></label><label>Poll interval ms<br><input id=pollIntervalMs></label></div><p><button onclick=saveCfg()>SAVE SETTINGS</button> <button onclick=p('/config/importlab')>IMPORT PROVEN LAB TIMING</button> <button onclick=p('/config/defaults')>RESTORE DEFAULTS</button></p><div class=muted>Full replay frame/timestamp values remain stored in NVS and defaults; the most commonly changed transport values are exposed here.</div></div>
<div class=c><b>Live/raw output</b><pre id=live></pre></div><div class=c><b>Raw transport log</b><p><button id=pauseRaw onclick=toggleRaw()>PAUSE</button> <button onclick=copyRaw()>COPY</button> <button onclick="window.location='/api/raw-log.txt'">EXPORT .TXT</button> <button onclick=p('/log/clear')>CLEAR LOG</button></p><div class=muted>Pause before selecting text. While paused, the page will not overwrite your selection.</div><pre id=log></pre></div><div class=c><b>Human-readable activity log</b><p><button id=pauseAct onclick=toggleAct()>PAUSE</button> <button onclick=copyAct()>COPY</button> <button onclick="window.location='/api/activity-log.txt'">EXPORT .TXT</button></p><pre id=actlog></pre></div>
<script>const $=x=>document.getElementById(x);let rawPaused=false,actPaused=false;async function p(u,b){let o={method:'POST'};if(b){o.headers={'Content-Type':'application/x-www-form-urlencoded'};o.body=new URLSearchParams(b)}let r=await fetch(u,o);let t=await r.text();if(!r.ok)alert(t);return t}async function sendRaw(){$('ans').textContent=await p('/payload',{x:$('raw').value})}async function refreshRelay(){try{let r=await(await fetch('/api/relay/status',{cache:'no-store'})).json();$('relayDiag').textContent=r.channels.map(c=>'Chip '+c.relay+': OBD '+c.obdPin+' RX '+c.gpio+' TX '+c.txGpio+(c.commandedOn?' [selected]':'')).join('\\n')}catch(e){$('relayDiag').textContent='Channel status unavailable: '+e}}async function clearDtc(){if(confirm('Clear engine DTC memory?'))await p('/dtc/clear')}async function loadCfg(){let c=await(await fetch('/config')).json();for(let k of ['baud','byteSpacingUs','fastLowUs','fastFirstByteUs','pollGroups','pollIntervalMs'])if($(k))$(k).value=c[k]}async function saveCfg(){let c=await(await fetch('/config')).json();let b={};for(let k in c)b[k]=c[k];for(let k of ['baud','byteSpacingUs','fastLowUs','fastFirstByteUs','pollGroups','pollIntervalMs'])b[k]=$(k).value;b.sendPostC1=c.sendPostC1;b.requirePostC1=c.requirePostC1;alert(await p('/config/save',b));await loadCfg()}function selectionActive(){return window.getSelection&&window.getSelection().toString().length>0}function toggleRaw(){rawPaused=!rawPaused;$('pauseRaw').textContent=rawPaused?'RESUME':'PAUSE'}function toggleAct(){actPaused=!actPaused;$('pauseAct').textContent=actPaused?'RESUME':'PAUSE'}async function copyText(id){try{await navigator.clipboard.writeText($(id).textContent)}catch(e){alert('Copy failed. Pause the log and select the text manually.')}}function copyRaw(){copyText('log')}function copyAct(){copyText('actlog')}async function tick(){try{$('st').textContent=JSON.stringify(await(await fetch('/status')).json(),null,2);$('live').textContent=(await(await fetch('/live')).json()).text;$('dtc').textContent=await(await fetch('/dtc')).text();if(!rawPaused&&!selectionActive())$('log').textContent=await(await fetch('/log',{cache:'no-store'})).text();if(!actPaused&&!selectionActive())$('actlog').textContent=await(await fetch('/api/activity-log',{cache:'no-store'})).text()}catch(e){}}loadCfg();refreshRelay();tick();setInterval(tick,1000);setInterval(refreshRelay,1000)</script></body></html>)HTML";}
