uint32_t lastDtcScanMs=0,lastWifiRetryMs=0;
void setupRoutes(){
web.on("/",HTTP_GET,[]{web.sendHeader("Cache-Control","no-store");web.send(200,"text/html; charset=utf-8",scannerPage());});
web.on("/advanced",HTTP_GET,[]{web.sendHeader("Cache-Control","no-store");web.send(200,"text/html; charset=utf-8",advancedPage());});
web.on("/update",HTTP_GET,[]{web.sendHeader("Cache-Control","no-store");web.send(200,"text/html; charset=utf-8",updatePage());});
web.on("/api/status",HTTP_GET,[]{web.send(200,"application/json",moduleStatusJson());});
web.on("/api/sensors",HTTP_GET,[]{web.send(200,"application/json",sensorsJson());});
web.on("/sensors",HTTP_GET,[]{web.send(200,"application/json",sensorsJson());});
web.on("/api/dtc",HTTP_GET,[]{web.send(200,"text/plain",dtcText);});
web.on("/api/module/connect",HTTP_POST,[]{if(busy||jobConnect){web.send(409,"text/plain","Scanner is busy");return;}int id=web.arg("id").toInt();if(id<0||id>2){web.send(400,"text/plain","Unknown module");return;}autoReconnect=true;requestedModule=(ModuleId)id;if(diagnosticSession)disconnectCurrentModule();activeModule=requestedModule;activeEcuAddr=moduleAddr(activeModule);dtcText=activeModule==MOD_ABS?"ABS DTC read request is not verified yet.":"No DTC read yet.";setStatus("CONNECT QUEUED - "+moduleName(activeModule));jobConnect=true;web.send(202,"text/plain","Connection queued");});
web.on("/api/disconnect",HTTP_POST,[]{if(busy){web.send(409,"text/plain","Busy");return;}autoReconnect=false;reconnectAtMs=0;disconnectCurrentModule();web.send(200,"text/plain","Disconnected");});
web.on("/api/poll/start",HTTP_POST,[]{if(!diagnosticSession){web.send(409,"text/plain","Connect the selected module first");return;}livePolling=true;nextPollMs=millis();web.send(200,"text/plain","Live data started");});
web.on("/api/poll/stop",HTTP_POST,[]{livePolling=false;web.send(200,"text/plain","Live data stopped");});
web.on("/api/dtc/read",HTTP_POST,[]{if(activeModule==MOD_ABS){readDTCs();web.send(501,"text/plain",dtcText);return;}if(!diagnosticSession||busy){web.send(409,"text/plain","Not connected or busy");return;}bool ok=readDTCs();lastDtcScanMs=millis();web.send(ok?200:500,"text/plain",dtcText);});
web.on("/status",HTTP_GET,[]{web.send(200,"application/json",statusJson());});web.on("/live",HTTP_GET,[]{web.send(200,"application/json",liveJson());});web.on("/dtc",HTTP_GET,[]{web.send(200,"text/plain",dtcText);});web.on("/log",HTTP_GET,[]{web.send(200,"text/plain",logText);});web.on("/log/clear",HTTP_POST,[]{logText="";web.send(200,"text/plain","CLEARED");});web.on("/config",HTTP_GET,[]{web.send(200,"application/json",configJson());});
web.on("/config/save",HTTP_POST,[]{if(busy||jobConnect){web.send(409,"text/plain","Busy");return;}ScannerConfig old=cfg;applyConfigFromWeb();String err=validateConfig();if(err.length()){cfg=old;applyPollGroups();web.send(400,"text/plain","NOT SAVED: "+err);return;}autoReconnect=false;livePolling=false;diagnosticSession=false;cr2Connected=false;releaseKL();applyPollGroups();saveScannerConfig();lastError="";setStatus("CONFIG SAVED - DISCONNECTED");web.send(200,"text/plain","Saved");});
web.on("/config/importlab",HTTP_POST,[]{if(busy||jobConnect){web.send(409,"text/plain","Busy");return;}importPriorLabTransport();applyPollGroups();saveScannerConfig();autoReconnect=false;livePolling=false;diagnosticSession=false;cr2Connected=false;releaseKL();setStatus("LAB TRANSPORT IMPORTED - DISCONNECTED");web.send(200,"text/plain","Imported proven lab timing");});
web.on("/config/defaults",HTTP_POST,[]{if(busy||jobConnect){web.send(409,"text/plain","Busy");return;}cfg=ScannerConfig();importPriorLabTransport();applyPollGroups();saveScannerConfig();autoReconnect=false;livePolling=false;diagnosticSession=false;cr2Connected=false;releaseKL();lastError="";setStatus("PROVEN DEFAULTS RESTORED - DISCONNECTED");web.send(200,"text/plain","Restored scanner defaults");});
web.on("/connect",HTTP_POST,[]{if(busy||jobConnect){web.send(409,"text/plain","Busy");return;}autoReconnect=true;requestedModule=MOD_ENGINE;activeModule=MOD_ENGINE;activeEcuAddr=0x12;jobConnect=true;web.send(202,"text/plain","ENGINE CONNECT QUEUED");});
web.on("/disconnect",HTTP_POST,[]{if(busy){web.send(409,"text/plain","Busy");return;}autoReconnect=false;reconnectAtMs=0;disconnectCurrentModule();web.send(200,"text/plain","DISCONNECTED");});
web.on("/poll/start",HTTP_POST,[]{if(!diagnosticSession){web.send(409,"text/plain","Connect first");return;}livePolling=true;nextPollMs=millis();web.send(200,"text/plain","LIVE POLLING STARTED");});
web.on("/poll/stop",HTTP_POST,[]{livePolling=false;web.send(200,"text/plain","LIVE POLLING STOPPED");});
web.on("/dtc/read",HTTP_POST,[]{if(!diagnosticSession||busy){web.send(409,"text/plain","Not connected or busy");return;}bool ok=readDTCs();web.send(ok?200:500,"text/plain",dtcText);});
web.on("/dtc/clear",HTTP_POST,[]{if(!diagnosticSession||busy){web.send(409,"text/plain","Not connected or busy");return;}bool ok=clearPowertrainDTCs();web.send(ok?200:500,"text/plain",ok?"DTC CLEAR ACCEPTED":lastError);});
web.on("/payload",HTTP_POST,[]{if(!diagnosticSession||busy){web.send(409,"text/plain","Not connected or busy");return;}String ans=sendManualPayload(web.arg("x"));web.send(ans.startsWith("Failed")?500:200,"text/plain",ans);});
web.on("/api/update-latest",HTTP_POST,[]{if(busy){web.send(409,"text/plain","Scanner busy");return;}autoReconnect=false;livePolling=false;diagnosticSession=false;releaseKL();String v,u,sha,r;if(!fetchLatestManifest(v,u,sha,r)){web.send(502,"text/plain","Manifest failed: "+r);return;}bool ok=installFirmwareFromUrl(u,sha,r);web.sendHeader("Connection","close");web.send(ok?200:500,"text/plain",ok?"Installed "+v+". "+r+". Rebooting...":r);if(ok){delay(800);ESP.restart();}});
web.on("/api/update",HTTP_POST,[]{bool ok=!Update.hasError();web.sendHeader("Connection","close");web.send(ok?200:500,"text/plain",ok?"Firmware installed. Rebooting...":String("Update failed: ")+Update.errorString());if(ok){delay(700);ESP.restart();}},[]{HTTPUpload&up=web.upload();if(up.status==UPLOAD_FILE_START){autoReconnect=false;livePolling=false;diagnosticSession=false;releaseKL();if(!up.filename.endsWith(".bin")){Update.abort();return;}Update.begin(UPDATE_SIZE_UNKNOWN,U_FLASH);}else if(up.status==UPLOAD_FILE_WRITE){if(!Update.hasError())Update.write(up.buf,up.currentSize);}else if(up.status==UPLOAD_FILE_END){if(!Update.hasError())Update.end(true);}else if(up.status==UPLOAD_FILE_ABORTED)Update.abort();});
}
void setup(){Serial.begin(115200);pinMode(RX_PIN,INPUT);loadAllSettings();releaseKL();WiFi.mode(WIFI_AP_STA);WiFi.softAP(apSSID.c_str(),apPASS.c_str());if(wifiSSID.length()){WiFi.begin(wifiSSID.c_str(),wifiPASS.c_str());uint32_t t=millis();while(WiFi.status()!=WL_CONNECTED&&millis()-t<8000)delay(100);}setupRoutes();web.begin();logx(String("T1N Scanner ")+FIRMWARE_VERSION+" ready");logx(String("AP http://")+WiFi.softAPIP().toString()+" | station "+(WiFi.status()==WL_CONNECTED?WiFi.localIP().toString():String("not connected")));setStatus("DISCONNECTED - SELECT MODULE");}
void loop(){web.handleClient();if(jobConnect&&!busy){jobConnect=false;connectModule(requestedModule);}livePollTick();if(diagnosticSession&&!busy&&activeModule!=MOD_ABS&&millis()-lastDtcScanMs>=15000){readDTCs();lastDtcScanMs=millis();}if(diagnosticSession&&!busy&&!livePolling&&millis()-lastGoodTrafficMs>=cfg.keepaliveIntervalMs){busy=true;testerPresent();busy=false;}if(!diagnosticSession&&autoReconnect&&reconnectAtMs&&(int32_t)(millis()-reconnectAtMs)>=0&&!busy&&!jobConnect){reconnectAtMs=0;jobConnect=true;setStatus("AUTO RECONNECT QUEUED - "+moduleName(requestedModule));}if(wifiSSID.length()&&WiFi.status()!=WL_CONNECTED&&millis()-lastWifiRetryMs>30000){lastWifiRetryMs=millis();WiFi.disconnect();WiFi.begin(wifiSSID.c_str(),wifiPASS.c_str());}delay(2);}
